<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class DailyValueSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('daily_values')->insert([[
        'valueable_id'      => 1    ,
        'valueable_type'     =>"App\Models\Player"   ,
        'daily_water_need'    => 8  ,
        'daily_water_intake'  =>  7 ,
        'daily_calorie_need'  => 2000  ,
        'daily_calorie_intake' => 1750 ,
        'daily_carb_need'     => 200  ,
        'daily_carb_intake'    => 100 ,
        'daily_protein_need'   => 90 ,
        'daily_protein_intake' => 55 ,
        'daily_fat_need'       => 10 ,
        'daily_fat_intake'     => 2 ,
        'daily_fibers_need'    => 10 , 
        'daily_fibers_intake'  => 2 ,
        ] ,
        ['valueable_id'      => 2    ,
        'valueable_type'     =>"App\Models\Player"   ,
        'daily_water_need'    => 8  ,
        'daily_water_intake'  => 0  ,
        'daily_calorie_need'  => 2000  ,
        'daily_calorie_intake' => 0 ,
        'daily_carb_need'     => 200  ,
        'daily_carb_intake'    => 0 ,
        'daily_protein_need'   => 90 ,
        'daily_protein_intake' => 0 ,
        'daily_fat_need'       => 10 ,
        'daily_fat_intake'     => 0 ,
        'daily_fibers_need'    => 10 , 
        'daily_fibers_intake'  => 0 ,
        ],
        ['valueable_id'      => 3    ,
        'valueable_type'     =>"App\Models\Player"   ,
        'daily_water_need'    => 8  ,
        'daily_water_intake'  => 1  ,
        'daily_calorie_need'  => 2000  ,
        'daily_calorie_intake' => 1000 ,
        'daily_carb_need'     => 200  ,
        'daily_carb_intake'    => 100 ,
        'daily_protein_need'   => 90 ,
        'daily_protein_intake' => 5 ,
        'daily_fat_need'       => 10 ,
        'daily_fat_intake'     => 10 ,
        'daily_fibers_need'    => 10 , 
        'daily_fibers_intake'  => 0 ,
        ],
        ['valueable_id'      => 4    ,
        'valueable_type'     =>"App\Models\Player"   ,
        'daily_water_need'    => 8  ,
        'daily_water_intake'  => 0  ,
        'daily_calorie_need'  => 2000  ,
        'daily_calorie_intake' => 0 ,
        'daily_carb_need'     => 200  ,
        'daily_carb_intake'    => 0 ,
        'daily_protein_need'   => 90 ,
        'daily_protein_intake' => 0 ,
        'daily_fat_need'       => 10 ,
        'daily_fat_intake'     => 0 ,
        'daily_fibers_need'    => 10 , 
        'daily_fibers_intake'  => 0 ,
        ],
        ['valueable_id'      => 5    ,
        'valueable_type'     =>"App\Models\Player"   ,
        'daily_water_need'    => 8  ,
        'daily_water_intake'  => 0  ,
        'daily_calorie_need'  => 2000  ,
        'daily_calorie_intake' => 0 ,
        'daily_carb_need'     => 200  ,
        'daily_carb_intake'    => 0 ,
        'daily_protein_need'   => 90 ,
        'daily_protein_intake' => 0 ,
        'daily_fat_need'       => 10 ,
        'daily_fat_intake'     => 0 ,
        'daily_fibers_need'    => 10 , 
        'daily_fibers_intake'  => 0 ,
        ],
        ['valueable_id'      => 1    ,
        'valueable_type'     =>"App\Models\Coach"   ,
        'daily_water_need'    => 8  ,
        'daily_water_intake'  => 0  ,
        'daily_calorie_need'  => 2000  ,
        'daily_calorie_intake' => 0 ,
        'daily_carb_need'     => 200  ,
        'daily_carb_intake'    => 0 ,
        'daily_protein_need'   => 90 ,
        'daily_protein_intake' => 0 ,
        'daily_fat_need'       => 10 ,
        'daily_fat_intake'     => 0 ,
        'daily_fibers_need'    => 10 , 
        'daily_fibers_intake'  => 0 ,
        ],
        ['valueable_id'      => 2    ,
        'valueable_type'     =>"App\Models\Coach"   ,
        'daily_water_need'    => 8  ,
        'daily_water_intake'  => 0  ,
        'daily_calorie_need'  => 2000  ,
        'daily_calorie_intake' => 0 ,
        'daily_carb_need'     => 200  ,
        'daily_carb_intake'    => 0 ,
        'daily_protein_need'   => 90 ,
        'daily_protein_intake' => 0 ,
        'daily_fat_need'       => 10 ,
        'daily_fat_intake'     => 0 ,
        'daily_fibers_need'    => 10 , 
        'daily_fibers_intake'  => 0 ,
        ],
        ['valueable_id'      => 3    ,
        'valueable_type'     =>"App\Models\Coach"   ,
        'daily_water_need'    => 8  ,
        'daily_water_intake'  => 0  ,
        'daily_calorie_need'  => 2000  ,
        'daily_calorie_intake' => 0 ,
        'daily_carb_need'     => 200  ,
        'daily_carb_intake'    => 0 ,
        'daily_protein_need'   => 90 ,
        'daily_protein_intake' => 0 ,
        'daily_fat_need'       => 10 ,
        'daily_fat_intake'     => 0 ,
        'daily_fibers_need'    => 10 , 
        'daily_fibers_intake'  => 0 ,
        ],
        ['valueable_id'      => 4    ,
        'valueable_type'     =>"App\Models\Coach"   ,
        'daily_water_need'    => 8  ,
        'daily_water_intake'  => 0  ,
        'daily_calorie_need'  => 2000  ,
        'daily_calorie_intake' => 0 ,
        'daily_carb_need'     => 200  ,
        'daily_carb_intake'    => 0 ,
        'daily_protein_need'   => 90 ,
        'daily_protein_intake' => 0 ,
        'daily_fat_need'       => 10 ,
        'daily_fat_intake'     => 0 ,
        'daily_fibers_need'    => 10 , 
        'daily_fibers_intake'  => 0 ,
        ],
        ['valueable_id'      => 5    ,
        'valueable_type'     =>"App\Models\Coach"   ,
        'daily_water_need'    => 8  ,
        'daily_water_intake'  => 0  ,
        'daily_calorie_need'  => 2000  ,
        'daily_calorie_intake' => 0 ,
        'daily_carb_need'     => 200  ,
        'daily_carb_intake'    => 0 ,
        'daily_protein_need'   => 90 ,
        'daily_protein_intake' => 0 ,
        'daily_fat_need'       => 10 ,
        'daily_fat_intake'     => 0 ,
        'daily_fibers_need'    => 10 , 
        'daily_fibers_intake'  => 0 ,
        ],

        ]
    
    );
    }
}
